apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata
  labels:
    app: db
    tier: data
spec:
  capacity:
    storage: 51M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.119
    path: "/exports/nfs"
    readOnly: false
