---
ansible_ssh_host: 192.168.100.111
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant
ansible_become_method: sudo
ansible_become_password: ""
ansible_ssh_private_key_file: "{{inventory_dir}}/../../../vagrant/.vagrant/machines/{{inventory_hostname}}/virtualbox/private_key"
